---
collections:
  - name: ansible.posix
    version: ">=2.1.0,<3.0.0"
  - name: community.general
    version: ">=12.4.0,<12.5.0"
  - name: community.docker
    version: ">=5.0.0,<5.1.0"

roles:
  - name: rolehippie.docker

...
